name = "medium-backend-2"
main = "src/index.ts"
compatibility_date = "2024-10-05"
compatibility_flags = [ "nodejs_compat" ]

 [vars]

 DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNWRhNDc1MjctNTIyMC00M2UzLWFkYTEtMjAyNjQwMzViYjI2IiwidGVuYW50X2lkIjoiNWNiMjk2ZjhiNmI4NjNmOWE4MDI2OGI0MGE1NmY1MGZkZjNhNzY1ZjI2NWJmOWVlYWU3ZmYzZDhlMGI5YTMxMiIsImludGVybmFsX3NlY3JldCI6IjI5YWQ0OTJiLTlmYTUtNGI1ZC1hZGVmLTA2ZWYxNzIzOTNmZSJ9.gP0C1jVvlgP8cW78eRa16fAV29qwQH9ojndDWU6JMW4"
 JWT_SECRET = "asdasdasd"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

 [[d1_databases]]
 binding = "DB"
 database_name = "user-prisma-api-2"
 database_id = "c4835c0d-3c05-4e99-b985-cc342c8f04ae"
 migrations_dir = "prisma/migrations"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1